spring:
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  data:
    mongodb:
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE}
      #      username: ${MONGO_USERNAME}
      #      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8082

topics: ${KAFKA_SUBSCRIBED_TOPICS}