version: "3.0"

networks:
  app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local

services:
  generator:
    image: 'qreol/data-generator-microservice'
    networks:
      - app
    depends_on:
      - kafka
    env_file:
      - .env
    ports:
      - "8081:8081"

  analyser:
    image: 'qreol/data-analyser-microservice'
    networks:
      - app
    depends_on:
      - mongo
      - kafka
    env_file:
      - .env
    ports:
      - "8082:8082"

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    networks:
      - app
    env_file:
      - .env
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    networks:
      - app
    env_file:
      - .env
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data

  mongo:
    image: 'mongo:latest'
    networks:
      - app
    ports:
      - "27018:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db